---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "192.168.1.101"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "P@ssw0rd"
    datacenter_name: "Datacenter"
  tasks:
  - name: Criar VM a partir do template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: Ubuntu-VM01
      template: Ubuntu 18
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      datastore: "datastore1"
      networks:
      - name: VM Network
        type: dhcp
      customization:
        hostname: "Ubuntu01"
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
