---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "192.168.1.101"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "P@ssw0rd"
    datacenter_name: "Datacenter"
    esxi_hostname: "192.168.1.102" 
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: Teste-VM
      guest_id: ubuntu64Guest
      esxi_hostname: "{{ esxi_hostname  }}"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      datastore: "datastore1"
      disk:
      - size_gb: 10
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 1024
        num_cpus: 1
        scsi: paravirtual      
      networks:
      - name: VM Network
        type: dhcp
      customization:
        hostname: "Ubuntu01"
      state: poweredoff
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy_vm
